CREATE TABLE WORKER
(
  ID 		 NUMBER PRIMARY KEY,
  FAMILY     VARCHAR2(64) NOT NULL,
  FIRST_NAME VARCHAR2(64) NOT NULL,
  SURNAME    VARCHAR2(64) NOT NULL
);

CREATE UNIQUE INDEX UNQ_WORKER ON WORKER(FAMILY, FIRST_NAME, SURNAME);