CREATE TABLE WORKER
(
  ID           NUMBER PRIMARY KEY,
  FAMILY       VARCHAR2(64) NOT NULL,
  FIRST_NAME   VARCHAR2(64) NOT NULL,
  SURNAME      VARCHAR2(64),
  BIRTHDAY     DATE         NOT NULL,
  SEX          VARCHAR2(16) NOT NULL,
  MOBILE_PHONE VARCHAR2(32),
  EMAIL        VARCHAR2(64) NOT NULL
);