CREATE TABLE WORKER_EVENT
(
  WORKER_ID   NUMBER NOT NULL,
  EVENT_ID    NUMBER NOT NULL
);

COMMENT ON TABLE WORKER_EVENT IS 'Таблица развязки работников и событий';
COMMENT ON COLUMN WORKER_EVENT.WORKER_ID IS 'Ссылка на работника';
COMMENT ON COLUMN WORKER_EVENT.EVENT_ID IS 'Ссылка на событие';

ALTER TABLE WORKER_EVENT ADD CONSTRAINT FK_WE_WORKER FOREIGN KEY (WORKER_ID) REFERENCES WORKER(ID);
ALTER TABLE WORKER_EVENT ADD CONSTRAINT FK_WE_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID);