CREATE TABLE WORK_DAY_EVENT_TYPE
(
  ID         NUMBER PRIMARY KEY,
  NAME       VARCHAR2(16)           NOT NULL,
  IS_WORKING NUMBER(1, 0) DEFAULT 1 NOT NULL,
  TIME       NUMBER DEFAULT 0       NOT NULL,
  IS_SYS     NUMBER DEFAULT 0       NOT NULL
);

COMMENT ON TABLE WORK_DAY_EVENT_TYPE IS 'События рабочего для: митинги, планирования, обеды и тд.';
COMMENT ON COLUMN WORK_DAY_EVENT_TYPE.ID IS 'PK';
COMMENT ON COLUMN WORK_DAY_EVENT_TYPE.NAME IS 'Наименование события';
COMMENT ON COLUMN WORK_DAY_EVENT_TYPE.IS_WORKING IS 'Считается ли событие рабочим';
COMMENT ON COLUMN WORK_DAY_EVENT_TYPE.TIME IS 'Время которое не считается недоработкой, для не рабочего события';
COMMENT ON COLUMN WORK_DAY_EVENT_TYPE.IS_SYS IS 'Является ли запись системной';

CREATE UNIQUE INDEX UNQ_WORK_DAY_EVENT_TYPE ON WORK_DAY_EVENT_TYPE (NAME);
