CREATE TABLE WORKER
(
  WORKER_ID  NUMBER PRIMARY KEY,
  FAMILY     VARCHAR2(64) NOT NULL,
  FIRST_NAME VARCHAR2(64) NOT NULL,
  SURNAME    VARCHAR2(64) NOT NULL
);

CREATE UNIQUE INDEX UNQ_WORKER ON WORKER(FAMILY, FIRST_NAME, SURNAME);

CREATE SEQUENCE GEN_WORKER_ID MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOPARTITION;

CREATE TABLE LOGIN
(
  WORKER_ID NUMBER       NOT NULL,
  LOGIN     VARCHAR2(32) NOT NULL,
  PASSWORD  VARCHAR2(32) NOT NULL
);

CREATE UNIQUE INDEX UNQ_WORKER ON LOGIN(LOGIN);

ALTER TABLE LOGIN ADD CONSTRAINT FK_LOGIN_WORKER FOREIGN KEY (WORKER_ID) REFERENCES WORKER (WORKER_ID);

CREATE TABLE WORK_DAY
(
  WORK_DAY_ID NUMBER PRIMARY KEY,
  WORKER_ID   NUMBER       NOT NULL,
  DAY_TYPE    VARCHAR2(16) NOT NULL,
  DAY         DATE         NOT NULL,
  COMING_TIME TIMESTAMP    NOT NULL,
  OUT_TIME    TIMESTAMP    NOT NULL,
  STATE       VARCHAR2(16) NOT NULL
);

CREATE UNIQUE INDEX UNQ_WORK_DAY ON WORK_DAY(WORKER_ID, DAY);

ALTER TABLE WORK_DAY ADD CONSTRAINT FK_WORK_DAY_WORKER FOREIGN KEY (WORKER_ID) REFERENCES WORKER (WORKER_ID);

CREATE SEQUENCE GEN_WORK_DAY_ID MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOPARTITION;