CREATE TABLE WORK_DAY_EVENT
(
  WORK_DAY_ID NUMBER NOT NULL,
  EVENT_ID    NUMBER NOT NULL
);

COMMENT ON TABLE WORK_DAY_EVENT IS 'Таблица развязки рабочих дней и событий';
COMMENT ON COLUMN WORK_DAY_EVENT.WORK_DAY_ID IS 'Ссылка на рабочий день';
COMMENT ON COLUMN WORK_DAY_EVENT.EVENT_ID IS 'Ссылка на событие';

ALTER TABLE WORK_DAY_EVENT ADD CONSTRAINT FK_WDE_WORK_DAY FOREIGN KEY (WORK_DAY_ID) REFERENCES WORK_DAY(ID);
ALTER TABLE WORK_DAY_EVENT ADD CONSTRAINT FK_WDE_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID);