CREATE TABLE WORK_DAY
(
  ID 		  NUMBER PRIMARY KEY,
  WORKER_ID   NUMBER       NOT NULL,
  DAY_TYPE    VARCHAR2(16) NOT NULL,
  DAY         DATE         NOT NULL,
  COMING_TIME TIMESTAMP    NOT NULL,
  OUT_TIME    TIMESTAMP    NOT NULL,
  STATE       VARCHAR2(16) NOT NULL
);

CREATE UNIQUE INDEX UNQ_WORK_DAY ON WORK_DAY(WORKER_ID, DAY);

ALTER TABLE WORK_DAY ADD CONSTRAINT FK_WORK_DAY_WORKER FOREIGN KEY (WORKER_ID) REFERENCES WORKER (ID);