DROP TABLE worker_event PURGE;
DROP TABLE event PURGE;
DROP TABLE event_type PURGE;
DROP TABLE work_day PURGE;
DROP TABLE DAY PURGE;
DROP TABLE login PURGE;
DROP TABLE worker PURGE;
DROP SEQUENCE gen_wa_id;